version: '3.3'

services:
  diary_db: 
    image: postgres:15.2
    container_name: diary_db
    restart: always
    environment: 
      POSTGRES_DB: ${TYPEORM_USERNAME}
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
    env_file: .env
    ports: 
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
volumes: 
  postgres: