version: '3.3'

services:
  diary_db: 
    image: postgres:15.2
    container_name: diary_db
    restart: always
    environment: 
      POSTGRES_DB: diarydb
      POSTGRES_USER: diaryMariachi
      POSTGRES_PASSWORD: diaryMariachi2023
    ports: 
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
volumes: 
  postgres: